name: Build

on:
  workflow_call:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: src/WebUI/ClientApp/package-lock.json

    - name: Install .NET
      uses: actions/setup-dotnet@v1

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Test
      run: dotnet test --no-build --configuration Release --filter "FullyQualifiedName!~AcceptanceTests"
