name: Publish

on:
  workflow_call:

jobs:
  publish-website:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Install .NET
      uses: actions/setup-dotnet@v1

    - name: .NET Publish
      run: |
        dotnet publish --configuration Release --runtime win-x86 --self-contained --output ./publish
      working-directory: ./src/WebUI/
  
    - name: Zip website
      run: |
        zip -r ./publish.zip .
      working-directory: ./src/WebUI/publish

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: website
        path: ./src/WebUI/publish/publish.zip
        if-no-files-found: error
